config:
  fromEmail: noreply@ezmails.xyz
  subjectPrefix: ''
  emailKeyPrefix: emailsPrefix/
  forwardMapping:
    info@example.com:
      - example.john@example.com
      - example.jen@example.com
    abuse@example.com:
      - example.jim@example.com
    "@example.com":
      - example.john@example.com
    info:
      - info@example.com